function [h,s] = GUIframe(s)
close
%% GUI params
s.bdratio  = 1886/1991;
s.figwidth = 1100;
s.axwidth  = 800;
s.yoffset  = 15;
s.xoffset  = 15;
s.panelLineColor = repmat(0.75, 1,3);
s.backgcolor     = repmat(0.95, 1,3);
s.fontcolor      = repmat(0.2, 1,3);
%% Figure
h.Figure = figure('GraphicsSmoothing', 'off', 'Resize','off','Name','Price explorer',...
    'MenuBar','None','Toolbar','none','NumberTitle','off','Color',s.backgcolor,...
    'Position',[400 ,100, s.figwidth, 790]);
%% Axis
h.Axis = axes('Parent',h.Figure,...
    'NextPlot','add',...
    'Color','white','Layer','Top','Box','on','Xtick',[],'Ytick',[],...
    'Xcolor',s.panelLineColor,'Ycolor',s.panelLineColor,...
    'Units','pix',...
    'Position',[s.xoffset, s.yoffset, s.axwidth, s.axwidth*s.bdratio]);
%% Spinner
iconsClassName = 'com.mathworks.widgets.BusyAffordance$AffordanceSize';
iconsSizeEnums = javaMethod('values',iconsClassName);
h.Spinner      = com.mathworks.widgets.BusyAffordance(iconsSizeEnums(2), 'Loading...please be patient');  % icon, label
[~,h.Spinnercomp] = javacomponent(h.Spinner.getComponent, [s.xoffset+s.axwidth/2-100, s.yoffset+s.axwidth*s.bdratio/2-40,200,80], h.Figure);
%% Stats panel
postprop = {'HorizontalAl','left','FontSize',10,'Units','pix'};
s.titheight = 25;
widthPostcode = 120;
% Postcode 
h.PostcodeLabel = annotation('textbox',...
    postprop{:},'Vert','baseline','Color',s.fontcolor,'Fontweight','bold',...
    'Backg','none','EdgeCo','none',...
    'String','Postcode lookup',...
    'Position',[s.axwidth-widthPostcode-7, s.axwidth*s.bdratio-s.titheight+10, widthPostcode, s.titheight]);
h.PostcodeEdit = uicontrol('Parent',h.Figure,...
    'Style','edit',...
    postprop{:},'Foreground',s.fontcolor,...
    'Position',[s.axwidth-widthPostcode, s.axwidth*s.bdratio-1.5*s.titheight, widthPostcode, s.titheight]);
%% Layers panel
panelprop = {'BorderType','line','Backg',s.backgcolor,'HighlightColor',s.panelLineColor, 'Units','normalized'};
checkprop = {'Style','checkbox', 'HorizontalAl','left','FontSize',10, 'Background',s.backgcolor,'Foreground',s.fontcolor, 'Units','normalized'};
textprop = {'Style','text', 'HorizontalAl','left','FontSize',10, 'Background',s.backgcolor,'Foreground',s.fontcolor, 'Units','normalized'};

% Container
heightLayers = 145;
h.Layerspanel.Handle = uipanel('Parent',h.Figure,...
    'BorderType','none','Backg',s.backgcolor,'HighlightColor',s.panelLineColor,...
    'Units','pix',...
    'Position',[2*s.xoffset+s.axwidth, s.yoffset + s.axwidth*s.bdratio-heightLayers, s.figwidth-3*s.xoffset-s.axwidth,heightLayers]);
% Title
h.Layerspanel.Title = uipanel('Parent',h.Layerspanel.Handle,...
    panelprop{:},...
    'Position',[0, 1-s.titheight/heightLayers, 1, s.titheight/heightLayers]);
xoffset = 8;
xoffset = xoffset/(s.figwidth-3*s.xoffset-s.axwidth);
h.Layerspanel.TitleString = uicontrol('Parent',h.Layerspanel.Title,...
    textprop{:},...
    'String','Layers',...
    'Position',[xoffset, 0, 1, .8]);
% Body
yoffset   = 8;
nchild    = 5;
rowheight = (heightLayers - s.titheight - (nchild+1)*yoffset)/nchild;
rowheight = rowheight/(heightLayers - s.titheight);
yoffset   = yoffset/(heightLayers-s.titheight);
h.Layerspanel.Body = uipanel('Parent',h.Layerspanel.Handle,...
    panelprop{:},...
    'Position',[0, 0, 1,1-s.titheight/heightLayers]);
% Map
h.Layerspanel.BodyCheckMap = uicontrol('Parent',h.Layerspanel.Body,...
    checkprop{:},'Value',1,...
    'String','Map','Tag','map',...
    'Position',[xoffset, 5*yoffset+4*rowheight, 1, rowheight]);
% Scatter
h.Layerspanel.BodyCheckDeals = uicontrol('Parent',h.Layerspanel.Body,...
    checkprop{:},...
    'String','Trades','Tag','scatter',...
    'Position',[xoffset, 4*yoffset+3*rowheight, 1, rowheight]);
% Boundaries
h.Layerspanel.BodyCheckBoundaries = uicontrol('Parent',h.Layerspanel.Body,...
    checkprop{:},...
    'String','Boundaries','Tag','boundaries',...
    'Position',[xoffset, 3*yoffset+2*rowheight, 1, rowheight]);
% Excluded
h.Layerspanel.BodyCheckBoundariesExcluded = uicontrol('Parent',h.Layerspanel.Body,...
    checkprop{:},...
    'String','Excluded boundaries','Tag','excluded',...
    'Position',[xoffset, 2*yoffset+rowheight, 1, rowheight]);
% Tiles
h.Layerspanel.BodyCheckTiles = uicontrol('Parent',h.Layerspanel.Body,...
    checkprop{:},...
    'String','Tiles','Tag','tiles',...
    'Position',[xoffset, yoffset, 1, rowheight]);
%% Tiles panel
checkprop = {'Style','radiobutton','Enable','off', 'HorizontalAl','left','FontSize',10, 'Background',s.backgcolor,'Foreground',s.fontcolor, 'Units','normalized'};
heightTiles = 100;
h.Tilespanel.Handle = uipanel('Parent',h.Figure,...
    'BorderType','none','Backg',s.backgcolor,'HighlightColor',s.panelLineColor,...
    'Units','pix',...
    'Position',[2*s.xoffset+s.axwidth, s.axwidth*s.bdratio-heightTiles-heightLayers, s.figwidth-3*s.xoffset-s.axwidth,heightTiles]);
% Title
h.Tilespanel.Title = uipanel('Parent',h.Tilespanel.Handle,...
    panelprop{:},...
    'Position',[0, 1-s.titheight/heightTiles, 1, s.titheight/heightTiles]);
h.Tilespanel.TitleString = uicontrol('Parent',h.Tilespanel.Title,...
    textprop{:},...
    'String','Tiles',...
    'Position',[xoffset, 0, 1, .8]);
% Body
yoffset   = 8;
nchild    = 3;
rowheight = (heightTiles - s.titheight - (nchild+1)*yoffset)/nchild;
rowheight = rowheight/(heightTiles-s.titheight);
yoffset   = yoffset/(heightTiles-s.titheight);
h.Tilespanel.Body = uibuttongroup('Parent',h.Tilespanel.Handle,...
    panelprop{:},...
    'Position',[0, 0, 1,1-s.titheight/heightTiles]);
% Average
h.Tilespanel.BodyRadioAvg = uicontrol('Parent',h.Tilespanel.Body,...
    checkprop{:},...
    'String','Average price','Tag','average',...
    'Position',[xoffset, 3*yoffset+2*rowheight, 1, rowheight]);
% Density
h.Tilespanel.BodyRadioWeighted = uicontrol('Parent',h.Tilespanel.Body,...
    checkprop{:},...
    'String','Area weighted price','Tag','weighted',...
    'Position',[xoffset, 2*yoffset+rowheight, 1, rowheight]);
% Trend
h.Tilespanel.BodyRadioTrend = uicontrol('Parent',h.Tilespanel.Body,...
    checkprop{:},...
    'String','Price trends','Tag','trend',...
    'Position',[xoffset, yoffset, 1, rowheight]);
%% Tileinfo panel
heightTilesinfo = 180;
h.Tilesinfopanel.Handle = uipanel('Parent',h.Figure,...
    'BorderType','none','Backg',s.backgcolor,'HighlightColor',s.panelLineColor,...
    'Units','pix',...
    'Position',[2*s.xoffset+s.axwidth, s.axwidth*s.bdratio-heightTiles-heightLayers-heightTilesinfo-s.yoffset,...
                s.figwidth-3*s.xoffset-s.axwidth,heightTilesinfo]);
% Title
h.Tilesinfopanel.Title = uipanel('Parent',h.Tilesinfopanel.Handle,...
    panelprop{:},...
    'Position',[0, 1-s.titheight/heightTilesinfo, 1, s.titheight/heightTilesinfo]);
h.Tilesinfopanel.TitleString = uicontrol('Parent',h.Tilesinfopanel.Title,...
    textprop{:},...
    'String','Tile info (click on a tile)',...
    'Position',[xoffset, 0, 1, .8]);
% Body
yoffset   = 8;
nchild    = 6.5;
rowheight = (heightTilesinfo - s.titheight - (nchild+1)*yoffset)/nchild;
rowheight = rowheight/(heightTilesinfo-s.titheight);
yoffset   = yoffset/(heightTilesinfo-s.titheight);
h.Tilesinfopanel.Body = uipanel('Parent',h.Tilesinfopanel.Handle,...
    panelprop{:},...
    'Position',[0, 0, 1,1-s.titheight/heightTilesinfo]);
% Name
h.Tilesinfopanel.BodyName = uicontrol('Parent',h.Tilesinfopanel.Body,...
    textprop{:},...
    'Tag','Name: ',...
    'Position',[xoffset, 6*yoffset+5*rowheight, 1-2*xoffset,2*rowheight]);
% Code
h.Tilesinfopanel.BodyCode = uicontrol('Parent',h.Tilesinfopanel.Body,...
    textprop{:},...
    'Tag','Code: ',...
    'Position',[xoffset, 5*yoffset+4*rowheight, 1,rowheight]);
% Area
h.Tilesinfopanel.BodyArea = uicontrol('Parent',h.Tilesinfopanel.Body,...
    textprop{:},...
    'Tag','Area (ha): ',...
    'Position',[xoffset, 4*yoffset+3*rowheight, 1,rowheight]);
% Ndeal
h.Tilesinfopanel.BodyNdeals = uicontrol('Parent',h.Tilesinfopanel.Body,...
    textprop{:},...
    'Tag','No. of deals: ',...
    'Position',[xoffset, 3*yoffset+2*rowheight, 1,rowheight]);
% Price
h.Tilesinfopanel.BodyPrice = uicontrol('Parent',h.Tilesinfopanel.Body,...
    textprop{:},'TooltipString',sprintf(['The statistic depends on the type of tile.\n',...
                                         'It is average price, price per hectar and trending indicator']),...
    'Tag','Statistic: ',...
    'Position',[xoffset, 2*yoffset+rowheight, 1,rowheight]);
% Rank
h.Tilesinfopanel.BodyRank = uicontrol('Parent',h.Tilesinfopanel.Body,...
    textprop{:},...
    'Tag','Rank: ',...
    'Position',[xoffset, yoffset, 1,rowheight]);
%% Pcodeinfo panel
heightPcodeinfo = 170;
h.Pcodeinfopanel.Handle = uipanel('Parent',h.Figure,...
    'BorderType','none','Backg',s.backgcolor,'HighlightColor',s.panelLineColor,...
    'Units','pix',...
    'Position',[2*s.xoffset+s.axwidth, s.axwidth*s.bdratio-heightTiles-heightLayers-heightTilesinfo-heightPcodeinfo-2*s.yoffset,...
                s.figwidth-3*s.xoffset-s.axwidth,heightPcodeinfo]);
% Title
h.Pcodeinfopanel.Title = uipanel('Parent',h.Pcodeinfopanel.Handle,...
    panelprop{:},...
    'Position',[0, 1-s.titheight/heightPcodeinfo, 1, s.titheight/heightPcodeinfo]);
h.Pcodeinfopanel.TitleString = uicontrol('Parent',h.Pcodeinfopanel.Title,...
    textprop{:},...
    'String','Postcode info (use lookup)',...
    'Position',[xoffset, 0, 1, .8]);
% Body
yoffset   = 8;
nchild    = 6;
rowheight = (heightPcodeinfo - s.titheight - (nchild+1)*yoffset)/nchild;
rowheight = rowheight/(heightPcodeinfo-s.titheight);
yoffset   = yoffset/(heightPcodeinfo-s.titheight);
h.Pcodeinfopanel.Body = uipanel('Parent',h.Pcodeinfopanel.Handle,...
    panelprop{:},...
    'Position',[0, 0, 1,1-s.titheight/heightPcodeinfo]);
% Postcode
h.Pcodeinfopanel.BodyPcode = uicontrol('Parent',h.Pcodeinfopanel.Body,...
    textprop{:},...
    'Tag','Postcode: ',...
    'Position',[xoffset, 6*yoffset+5*rowheight, 1, rowheight]);
% Ndeal
h.Pcodeinfopanel.BodyNdeals = uicontrol('Parent',h.Pcodeinfopanel.Body,...
    textprop{:},...
    'Tag','No. of deals: ',...
    'Position',[xoffset, 5*yoffset+4*rowheight, 1,rowheight]);
% Between
h.Pcodeinfopanel.BodyBetween = uicontrol('Parent',h.Pcodeinfopanel.Body,...
    textprop{:},...
    'Tag','Between: ',...
    'Position',[xoffset, 4*yoffset+3*rowheight, 1,rowheight]);
% Average price
h.Pcodeinfopanel.BodyPrice = uicontrol('Parent',h.Pcodeinfopanel.Body,...
    textprop{:},...
    'Tag','Average price: ',...`
    'Position',[xoffset, 3*yoffset+2*rowheight, 1,rowheight]);
% Percentage new
h.Pcodeinfopanel.BodyPernew = uicontrol('Parent',h.Pcodeinfopanel.Body,...
    textprop{:},...
    'Tag','% new: ',...
    'Position',[xoffset, 2*yoffset+rowheight, 1,rowheight]);
% Percentage free
h.Pcodeinfopanel.BodyPerfree = uicontrol('Parent',h.Pcodeinfopanel.Body,...
    textprop{:},...
    'Tag','% free: ',...
    'Position',[xoffset, yoffset, 1,rowheight]);
end